--- 
about_section_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
about_section_heading: "About <strong>Me</strong>"
author_Github: "http://github.com/sonumeewa/coda-jekyll-theme-starter"
author_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
author_facebook: "http://facebook.com/sonumeewa"
author_image_landscape: /assets/img/avatar/1.jpg
author_image_portrait: /assets/img/avatar/1.jpg
author_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
author_name: "Coda Jekyll Theme>"
author_twitter: "http://twitter.com/VipulBarodiya"
blog_carousel_backgrounds: 
  - 
    image: "https://mdbootstrap.com/img/Photos/Others/city11.jpg"
  - 
    image: "https://mdbootstrap.com/img/Photos/Others/city13.jpg"
blog_list_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
blog_list_heading: "Welcome to my <strong>Blog</strong>"
blog_list_subheading: "All Blogs"
category_blog_list_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
category_blog_list_heading: "Welcome to my <strong>Blog</strong>"
category_blog_list_subheading: "Category: {{ page.category }}"
contact_section_card_button_text: Connect
contact_section_card_button_url: "http://www.linkedin.com/in/sonumeewa"
contact_section_card_heading: "@<strong>sonumeewa</strong>"
contact_section_card_image: "https://mdbootstrap.com/img/illustrations/graphics(4).png"
contact_section_card_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
contact_section_heading: "Get in <strong>Touch</strong>"
copyright_name: Vipul <strong>Barodiya</strong>
copyright_url: "http://github.com/sonumeewa/coda-jekyll-theme-starter"
copyright_year: 2019
experience: 
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    duration: "Feb, 2018 - Oct, 2018 (7 months)"
    title: "Backend developer - Zenedo"
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    duration: "July, 2018 - present"
    title: "Executive member, AASF developers' circle"
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    duration: "Aug, 2017 - Oct, 2017 (2 months)"
    title: "Web developer Intern - Shaastra LLP"
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    duration: "June 2013 - present"
    title: "NTSE scholar"
main_carousel_avatar: /assets/img/avatar/1.jpg
main_carousel_backgrounds: 
  - src: /assets/img/carousel/09.jpg
  - src: /assets/img/carousel/10.jpg
  - src: /assets/img/carousel/03.jpg
  - src: /assets/img/carousel/04.jpg
  - src: /assets/img/carousel/05.jpg
  - src: /assets/img/carousel/01.jpg
  - src: /assets/img/carousel/02.jpg
  - src: /assets/img/carousel/08.jpg
  - src: /assets/img/carousel/12.jpg
  
main_carousel_name: "Vipul <strong>Barodiya</strong>"
main_carousel_quote_1: "I'm like a tree"
main_carousel_quote_2: "My leaves might change color"
main_carousel_quote_3: "but my roots are the same"
main_carousel_quote_author: Rose Namajunas
main_carousel_socials: 
  - 
    link: "http://www.github.com/sonumeewa"
    name: github
  - 
    link: "http://www.linkedin.com/in/sonumeewa"
    name: linkedin
  - 
    link: "http://www.twitter.com/VipulBarodiya"
    name: twitter
  - 
    link: "mailto:test@test.com"
    name: envelope
navbar_avatar: /assets/img/1.png
navbar_name: "Vipul Barodiya"
navbar_navitems: 
  - 
    img: /assets/img/1.png
    link: /
    type: avatar
  - 
    brand: "Vipul Barodiya"
    link: /
    type: navbrand
  - 
    link: /
    name: Home
    type: item
  - 
    link: "/#about"
    name: About
    type: item
  - 
    link: "/#projects"
    name: Projects
    type: item
  - 
    link: "/#contact"
    name: Contact
    type: item
  - 
    link: /blog/
    name: Blog
    type: dropdown
professions: 
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    icon: fas fa-laptop white-text
    color:  aqua-gradient
    text_color: white-text
    name: Binge -Viewer
  - 
    icon: fas fa-code white-text
    color: unique-color-dark
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    text_color: white-text
    name: Developer
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    icon: fab fa-twitter white-text
    name: Social
    color:  blue-gradient
    text_color: white-text
  - 
    icon: fas fa-book white-text
    color: purple-gradient
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    text_color: white-text
    name: Reader
  - 
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    icon: fas fa-pencil-alt white-text
    name: Free Verser
    color: peach-gradient 
    text_color: white-text
projects: 
  - 
    button_text: Github
    button_url: "http://github.com/mathewsachin/BTP"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "Footstep recognition using Deep learning models"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
  - 
    button_text: Github
    button_url: "http://github.com/sonumeewa/coda-jekyll-theme-starter"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "Web Application (Ad Agency Manager)"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"

  - 
    button_text: Github
    button_url: "http://rubygems.org/coda-jekyll-theme"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "Coda-jekyll-theme"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
  - 
    button_text: Github
    button_url: "http://github.com/alien-invasion/"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "Alien Invasion"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
  - 
    button_text: Github
    button_url: "http://github.com/sonumeewa/coda-jekyll-theme-starter"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "Online Compiler"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
  - 
    button_text: Github
    button_url: "http://github.com/sonumeewa/coda-jekyll-theme-starter"
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
    image: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
    name: "NewsFeed"
    url: "https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
projects_section_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
 - Lynda Resnick"
projects_section_heading: "My <strong>Projects</strong>"
skills: 
  - 
    name: Data Structure
    percentage: 25
  - 
    name: Algortihms
    percentage: 25
  - 
    name: Backend devlopment (Node.js, Django)
    percentage: 25
  - 
    name: Rest APIs (Express)
    percentage: 25
  -
    name: C++
    percentage: 25
  -
    name: Javascript
    percentage: 25
  -
    name: python
    percentage: 25
    
tag_blog_list_heading: "Welcome to my <strong>Blog</strong>"
tag_blog_list_subheading: "Tag: {{ page.tag }}"
tag_blog_list_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante nibh, facilisis cursus dolor id, malesuada feugiat tortor. In egestas facilisis mauris. Integer euismod nunc ac ultricies laoreet. Nulla iaculis felis augue, non tincidunt dolor"
socials:
- link: https://www.facebook.com/sonumeewa
  name: facebook
- link: https://www.github.com/sonumeewa
  name: github
- link: https://www.twitter.com/VipulBarodiya
  name: twitter
- link: https://www.instagram.com/VipulBarodiya1
  name: instagram
- link: https://www.codepen.io/sonumeewa
  name: codepen
- link: https://www.pintereset.com/sonumeewa
  name: pinterest
- link: https://www.linkedin.com/in/sonumeewa
  name: linkedin